const express = require('express');
const { supabaseAdmin } = require('../supabaseClient');
const { issueSession } = require('../auth/session');

const router = express.Router();

// UUID v4 validation regex
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * POST /api/device/register
 * Body: { device_id: string }   (UUID v4 generated by the client)
 *
 * Idempotent: the same device_id always returns a token for the same user row.
 * No personal data is collected — only the anonymous UUID.
 *
 * Flow:
 *   1. Validate the UUID format.
 *   2. Look up the devices table for this device_id.
 *   3. If found → return a token for the associated user_id.
 *   4. If not found → insert a new user row, then a device row pointing to it.
 */
router.post('/register', async (req, res) => {
  const { device_id: deviceId } = req.body;

  if (!deviceId || !UUID_RE.test(deviceId)) {
    return res.status(400).json({ error: 'A valid UUID v4 device_id is required.' });
  }

  try {
    // Step 1 — check for an existing device registration
    const { data: existing, error: lookupError } = await supabaseAdmin
      .from('devices')
      .select('user_id')
      .eq('id', deviceId)
      .maybeSingle();

    if (lookupError) {
      console.error('Device lookup error:', lookupError);
      return res.status(500).json({ error: 'Unable to register device.' });
    }

    if (existing) {
      // Already registered — return a fresh token for the same user
      return res.json({ token: issueSession(existing.user_id), device_id: deviceId });
    }

    // Step 2 — new device: create an anonymous user row
    const { data: newUser, error: userError } = await supabaseAdmin
      .from('users')
      .insert({ name: `device:${deviceId}`, age: 18 }) // age satisfies CHECK(age>=5)
      .select('id')
      .single();

    if (userError) {
      console.error('User creation error:', userError);
      return res.status(500).json({ error: 'Unable to register device.' });
    }

    // Step 3 — register the device
    const { error: deviceError } = await supabaseAdmin
      .from('devices')
      .insert({ id: deviceId, user_id: newUser.id });

    if (deviceError) {
      console.error('Device insert error:', deviceError);
      // Clean up the orphaned user row on failure
      await supabaseAdmin.from('users').delete().eq('id', newUser.id);
      return res.status(500).json({ error: 'Unable to register device.' });
    }

    return res.status(201).json({ token: issueSession(newUser.id), device_id: deviceId });
  } catch (err) {
    console.error('Device registration unexpected error:', err);
    const isSessionConfigError = err.message?.includes('APP_SESSION_SECRET');
    return res.status(500).json({
      error: isSessionConfigError
        ? 'Server session setup is incomplete. Add APP_SESSION_SECRET and restart the backend.'
        : 'Unable to register device.',
    });
  }
});

/**
 * GET /api/device/count
 * Returns the total number of unique registered devices (user/device counter).
 * No authentication required — it's a public aggregate count.
 */
router.get('/count', async (_req, res) => {
  try {
    const { count, error } = await supabaseAdmin
      .from('devices')
      .select('*', { count: 'exact', head: true });

    if (error) {
      console.error('Device count error:', error);
      return res.status(500).json({ error: 'Unable to retrieve device count.' });
    }

    return res.json({ count });
  } catch (err) {
    console.error('Device count unexpected error:', err);
    return res.status(500).json({ error: 'Unable to retrieve device count.' });
  }
});

module.exports = router;
