export const AFTER_SALAH_DHIKR = [
  {
    id: 1,
    title: 'Istighfar',
    count: 3,
    arabic: 'أَسْتَغْفِرُ اللَّهَ',
    transliteration: 'Astaghfirullah',
    tamil: 'நான் அல்லாஹ்விடம் பாவமன்னிப்புத் தேடுகிறேன்.',
    reference: 'Sahih Muslim 591',
  },
  {
    id: 2,
    title: 'Peace Supplication',
    count: 1,
    arabic: 'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ ذَا الْجَلَالِ وَالْإِكْرَامِ',
    transliteration: 'Allahumma antas-salam wa minkas-salam, tabarakta ya dhal-jalali wal-ikram',
    tamil: 'யா அல்லாஹ்! நீயே சாந்தியளிப்பவன்; உன்னிடமிருந்தே சாந்தி கிடைக்கிறது. கண்ணியமும், மகத்துவமும் மிக்கவனே! நீ பாக்கியமுடையவன்.',
    reference: 'Sahih Muslim 591',
  },
  {
    id: 3,
    title: 'Declaration of Faith',
    count: 1,
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd, wa huwa \'ala kulli shay\'in qadir',
    tamil: 'வணக்கத்திற்குரியவன் அல்லாஹ்வைத் தவிர வேறு யாருமில்லை. அவன் தனித்தவன்; அவனுக்கு இணையில்லை. ஆட்சியும் புகழும் அவனுக்கே உரியன. அவன் அனைத்தின் மீதும் பேராற்றல் உடையவன்.',
    reference: 'Sahih al-Bukhari 844',
  },
  {
    id: 4,
    title: 'Submission to Allah\'s Will',
    count: 1,
    arabic: 'اللَّهُمَّ لَا مَانِعَ لِمَا أَعْطَيْتَ، وَلَا مُعْطِيَ لِمَا مَنَعْتَ، وَلَا يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ',
    transliteration: 'Allahumma la mani\'a lima a\'tayta, wa la mu\'tiya lima mana\'ta, wa la yanfa\'u dhal-jaddi minkal-jadd',
    tamil: 'யா அல்லாஹ்! நீ கொடுப்பதை தடுப்பார் எவருமில்லை; நீ தடுப்பதை கொடுப்பார் எவருமில்லை. செல்வந்தரின் செல்வம் உன்னிடம் எந்தப் பயனும் அளிக்காது (உன் அருளே பயன் தரும்).',
    reference: 'Sahih al-Bukhari 844',
  },
  {
    id: 5,
    title: 'Help in Remembrance',
    count: 1,
    arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ، وَشُكْرِكَ، وَحُسْنِ عِبَادَتِكَ',
    transliteration: "Allahumma a'inni 'ala dhikrika, wa shukrika, wa husni 'ibadatik",
    tamil: 'யா அல்லாஹ்! உன்னை நினைவுகூரவும், உனக்கு நன்றி செலுத்தவும், உன்னை அழகிய முறையில் வணங்கவும் எனக்கு உதவி செய்வாயாக.',
    reference: 'Sunan Abu Dawud 1522',
  },
  {
    id: 6,
    title: 'Tasbeeh, Tahmeed, Takbeer',
    count: 33,
    arabic: 'سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَاللَّهُ أَكْبَرُ',
    transliteration: 'Subhanallah (33x), Alhamdulillah (33x), Allahu Akbar (33x)',
    tamil: 'அல்லாஹ் தூயவன் (33 முறை), அல்ஹம்துலில்லாஹ் - புகழனைத்தும் அல்லாஹ்வுக்கே (33 முறை), அல்லாஹ் மிகப்பெரியவன் (33 முறை).',
    reference: 'Sahih Muslim 597',
  },
  {
    id: 7,
    title: 'Completing the 100',
    count: 1,
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd, wa huwa \'ala kulli shay\'in qadir',
    tamil: '(நூறைப் பூர்த்தி செய்ய ஒரு முறை ஓதவும்) வணக்கத்திற்குரியவன் அல்லாஹ்வைத் தவிர வேறு யாருமில்லை. அவன் தனித்தவன்; அவனுக்கு இணையில்லை.',
    reference: 'Sahih Muslim 597',
  },
  {
    id: 8,
    title: 'Ayatul Kursi (ஆயத்துல் குர்ஸி)',
    count: 1,
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    transliteration: "Allahu laaa ilaaha illaa Huwal Haiyul Qaiyoom; laa ta'khuzuhoo sinatunw wa laa nawm; lahoo maa fis samaawaati wa maa fil ard; man zal lazee yashfa'u 'indahooo illaa bi-iznih; ya'lamu maa baina aideehim wa maa khalfahum wa laa yuheetoona bishai'im min 'ilmiheee illaa bimaa shaaa'; wasi'a Kursiyyuhus samaawaati wal arda wa laa ya'ooduho hifzuhumaa; wa Huwal 'Aliyyul 'Azeem",
    tamil: 'அல்லாஹ் - அவனைத் தவிர வணக்கத்திற்குரிய நாயன் வேறு யாருமில்லை. அவன் என்றென்றும் உயிருடன் இருப்பவன்; (எல்லாவற்றையும்) நிர்வகிப்பவன். அவனை சிறு உறக்கமும் பீடிக்காது, தூக்கமும் பீடிக்காது. வானங்களில் உள்ளவையும் பூமியில் உள்ளவையும் அவனுக்கே உரியன. அவன் அனுமதி இன்றி அவனிடம் யார் தான் பரிந்து பேச முடியும்? அவர்களுக்கு முன்னால் இருப்பவற்றையும், அவர்களுக்குப் பின்னால் இருப்பவற்றையும் அவன் அறிவான். அவன் அறிவிலிருந்து எதையும், அவன் நாடினால் தவிர, அவர்களால் அறிந்துகொள்ள முடியாது. அவனது குர்ஸி (ஆசனம்) வானங்கள், பூமி ஆகியவற்றை விடப் பரந்து விரிந்துள்ளது. அவ்விரண்டையும் பாதுகாப்பது அவனுக்குச் சிரமமானதல்ல. அவன் மிக உயர்ந்தவன்; மகத்துவமிக்கவன்.\n\nநபி (ஸல்) அவர்கள் கூறினார்கள்: "ஒவ்வொரு கடமையான தொழுகைக்குப் பின்னும் ஆயத்துல் குர்ஸியை ஓதுபவரை சொர்க்கத்தில் நுழைவதிலிருந்து மரணம் தவிர வேறெதுவும் தடுக்காது."',
    reference: "Sunan an-Nasa'i (Al-Kubra) 9848",
  },
  {
    id: 9,
    title: 'The 3 Quls (Al-Ikhlas, Al-Falaq, An-Nas)',
    count: '1 or 3',
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ... | قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ... | قُلْ أَعُوذُ بِرَبِّ النَّاسِ...',
    transliteration: 'Surah Al-Ikhlas, Surah Al-Falaq, Surah An-Nas',
    tamil: 'இந்த மூன்று அத்தியாயங்களையும் ஒவ்வொரு தொழுகைக்குப் பின்னும் ஒரு முறையும், ஃபஜ்ர் மற்றும் மஃரிப் தொழுகைகளுக்குப் பின் மூன்று முறையும் ஓத வேண்டும்.',
    reference: 'Sunan Abu Dawud 1523',
  }
];
