// ============================================
// DUA DATA
// Curated, sourced duas with full references
// ============================================

export const DUA_CATEGORIES = [
  { id: 'morning', name: 'Morning Adhkar', tamil: 'காலை துஆ', icon: '' },
  { id: 'evening', name: 'Evening Adhkar', tamil: 'மாலை துஆ', icon: '' },
  { id: 'sleep', name: 'Before Sleep', tamil: 'தூக்கத்திற்கு முன்', icon: '' },
  { id: 'wakeup', name: 'Upon Waking', tamil: 'விழிப்பு துஆ', icon: '️' },
  { id: 'prayer', name: 'After Prayer', tamil: 'தொழுகைக்குப் பின்', icon: '' },
  { id: 'food', name: 'Food & Eating', tamil: 'உணவு துஆ', icon: '️' },
  { id: 'travel', name: 'Travel', tamil: 'பயண துஆ', icon: '' },
  { id: 'masjid', name: 'Masjid', tamil: 'மஸ்ஜித் துஆ', icon: '' },
  { id: 'forgiveness', name: 'Forgiveness', tamil: 'மன்னிப்பு துஆ', icon: '' },
  { id: 'parents', name: 'For Parents', tamil: 'பெற்றோர் துஆ', icon: '️' },
  { id: 'anxiety', name: 'Anxiety & Grief', tamil: 'கவலை துஆ', icon: '' },
  { id: 'protection', name: 'Protection', tamil: 'பாதுகாப்பு துஆ', icon: '️' },
  { id: 'rizq', name: 'For Rizq', tamil: 'ரிஸ்க் துஆ', icon: '' },
  { id: 'ramadan', name: 'Ramadan', tamil: 'ரமழான் துஆ', icon: '' },
  { id: 'illness', name: 'Illness & Health', tamil: 'நோய் துஆ', icon: '' },
  { id: 'marriage', name: 'Marriage', tamil: 'திருமணம்', icon: '' },
];

export const DUAS = [
  // MORNING
  {
    id: 'morning-1',
    category: 'morning',
    title: 'Morning Supplication',
    tamil: 'காலை துஆ — விழிப்புக்குப் பின்',
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ',
    transliteration: "Allahumma bika asbahna wa bika amsayna wa bika nahya wa bika namutu wa ilayk al-nushur",
    meaning_tamil: 'அல்லாஹ்வே! உன்னால் காலை வந்தோம், உன்னால் மாலை வந்தோம், உன்னால் வாழ்கிறோம், உன்னால் இறக்கிறோம், உன்னிடமே மீளுவோம்.',
    meaning_english: 'O Allah, by You we enter the morning and by You we enter the evening, by You we live and by You we die, and to You is the resurrection.',
    reference: 'Sunan Abu Dawud 5068',
    source: 'Abu Dawud',
    grade: 'Sahih',
    count: 1,
  },
  {
    id: 'morning-2',
    category: 'morning',
    title: 'Morning Remembrance of Allah',
    tamil: 'அல்லாஹ்வை காலையில் போற்றுதல்',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'Subhana Allahi wa bihamdihi',
    meaning_tamil: 'அல்லாஹ் தூய்மையானவன், அவனுக்கே புகழ் உரித்தானது.',
    meaning_english: 'Glory be to Allah and all praise is due to Him.',
    reference: 'Sahih al-Bukhari 6405, Sahih Muslim 2692',
    source: 'Bukhari & Muslim',
    grade: 'Sahih',
    count: 100,
    note: 'Whoever says this 100 times in a day, 1000 good deeds are recorded for him or 1000 sins are wiped away. (Sahih Muslim 2691)',
  },
  {
    id: 'morning-3',
    category: 'morning',
    title: 'Morning Protection Dua',
    tamil: 'காலை பாதுகாப்பு துஆ',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ',
    transliteration: "Allahumma inni as'aluka al-'afiyata fi al-dunya wa al-akhirah",
    meaning_tamil: 'அல்லாஹ்வே! இவ்வுலகிலும் மறுவுலகிலும் ஆரோக்கியத்தை உன்னிடம் வேண்டுகிறேன்.',
    meaning_english: 'O Allah, I ask You for well-being in this world and in the Hereafter.',
    reference: 'Sunan Ibn Majah 3871',
    source: 'Ibn Majah',
    grade: 'Sahih',
    count: 1,
  },

  // EVENING
  {
    id: 'evening-1',
    category: 'evening',
    title: 'Evening Supplication',
    tamil: 'மாலை துஆ',
    arabic: 'اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ',
    transliteration: "Allahumma bika amsayna wa bika asbahna wa bika nahya wa bika namutu wa ilayk al-masir",
    meaning_tamil: 'அல்லாஹ்வே! உன்னால் மாலை வந்தோம், உன்னால் காலை வந்தோம், உன்னால் வாழ்கிறோம், உன்னால் இறக்கிறோம், உன்னிடமே மீளுவோம்.',
    meaning_english: 'O Allah, by You we enter the evening and by You we enter the morning, by You we live and by You we die, and to You is the return.',
    reference: 'Sunan Abu Dawud 5068',
    source: 'Abu Dawud',
    grade: 'Sahih',
    count: 1,
  },

  // SLEEP
  {
    id: 'sleep-1',
    category: 'sleep',
    title: 'Before Going to Sleep',
    tamil: 'தூங்குவதற்கு முன் துஆ',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismika Allahumma amutu wa ahya',
    meaning_tamil: 'அல்லாஹ்வே! உன் நாமத்தில் இறக்கிறேன் (தூங்குகிறேன்) உன் நாமத்தில் உயிர்க்கிறேன் (விழிக்கிறேன்).',
    meaning_english: 'In Your name, O Allah, I die and I live.',
    reference: 'Sahih al-Bukhari 6324',
    source: 'Bukhari',
    grade: 'Sahih',
    count: 1,
  },
  {
    id: 'sleep-2',
    category: 'sleep',
    title: 'Dua Before Sleeping — Al-Kafirun',
    tamil: 'தூக்கத்திற்கு முன் — சூரா அல்-காஃபிரூன்',
    arabic: 'قُلْ يَا أَيُّهَا الْكَافِرُونَ...',
    transliteration: "Qul ya ayyuha al-kafirun...",
    meaning_tamil: 'சூரத்துல் காஃபிரூன் (109வது அத்தியாயம்) — இதை தூங்குவதற்கு முன் ஓதுவது சுன்னத்.',
    meaning_english: 'Recite Surah Al-Kafirun (Chapter 109) before sleeping.',
    reference: 'Sunan Abu Dawud 5055',
    source: 'Abu Dawud',
    grade: 'Sahih',
    count: 1,
    note: 'It is a declaration of freedom from shirk.',
  },

  // WAKE UP
  {
    id: 'wakeup-1',
    category: 'wakeup',
    title: 'Upon Waking Up',
    tamil: 'தூங்கி எழுந்தவுடன் துஆ',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: "Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur",
    meaning_tamil: 'எங்களை மரணிக்கச் செய்த பின் உயிர்ப்பித்த அல்லாஹ்வுக்கே எல்லாப் புகழும். மேலும் அவனிடமே நாம் திரும்பிச் செல்ல வேண்டியுள்ளது.',
    meaning_english: 'All praise is to Allah who gave us life after having taken it from us and unto Him is the resurrection.',
    reference: 'Sahih al-Bukhari 6312',
    source: 'Bukhari',
    grade: 'Sahih',
    count: 1,
  },
  {
    id: 'wakeup-2',
    category: 'wakeup',
    title: 'Declaration of Faith upon Waking',
    tamil: 'விழித்ததும் ஓதும் கலிமா',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu, wa huwa 'ala kulli shay'in qadir",
    meaning_tamil: 'வணக்கத்திற்குரியவன் அல்லாஹ்வைத் தவிர வேறு யாருமில்லை. அவன் தனித்தவன், அவனுக்கு இணையில்லை. ஆட்சியும் புகழும் அவனுக்கே. அவன் அனைத்தின் மீதும் பேராற்றல் உடையவன்.',
    meaning_english: 'None has the right to be worshipped but Allah alone, Who has no partner. His is the dominion and to Him belongs all praise, and He is Able to do all things.',
    reference: 'Sahih al-Bukhari 1154',
    source: 'Bukhari',
    grade: 'Sahih',
    count: 1,
  },

  // AFTER PRAYER
  {
    id: 'prayer-1',
    category: 'prayer',
    title: 'Istighfar after Salah',
    tamil: 'தொழுகைக்குப் பின் இஸ்திஃஃபார்',
    arabic: 'أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ. اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ ذَا الْجَلَالِ وَالْإِكْرَامِ',
    transliteration: "Astaghfirullah (x3). Allahumma antas-salam wa minkas-salam, tabarakta ya dhal-jalali wal-ikram",
    meaning_tamil: 'அல்லாஹ்விடம் பாவமன்னிப்புத் தேடுகிறேன் (3 முறை). யா அல்லாஹ்! நீயே சாந்தியளிப்பவன், உன்னிடமிருந்தே சாந்தி கிடைக்கிறது. கண்ணியமும் மகத்துவமும் மிக்கவனே! நீ பாக்கியமுடையவன்.',
    meaning_english: 'I seek the forgiveness of Allah (three times). O Allah, You are Peace and from You comes peace. Blessed are You, O Owner of majesty and honor.',
    reference: 'Sahih Muslim 591',
    source: 'Muslim',
    grade: 'Sahih',
    count: 1,
  },
  {
    id: 'prayer-2',
    category: 'prayer',
    title: 'Dua for Help in Remembrance',
    tamil: 'அல்லாஹ்வை நினைவுகூர உதவி கோரும் துஆ',
    arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ، وَشُكْرِكَ، وَحُسْنِ عِبَادَتِكَ',
    transliteration: "Allahumma a'inni 'ala dhikrika, wa shukrika, wa husni 'ibadatik",
    meaning_tamil: 'யா அல்லாஹ்! உன்னை நினைவுகூரவும், உனக்கு நன்றி செலுத்தவும், உன்னை அழகிய முறையில் வணங்கவும் எனக்கு உதவி செய்வாயாக.',
    meaning_english: 'O Allah, help me to remember You, to give You thanks, and to perform Your worship in the best manner.',
    reference: 'Sunan Abu Dawud 1522',
    source: 'Abu Dawud',
    grade: 'Sahih',
    count: 1,
    note: 'The Prophet ﷺ advised Mu\'adh ibn Jabal to never leave this dua at the end of every prayer.',
  },
  {
    id: 'prayer-3',
    category: 'prayer',
    title: 'Protection from Hellfire (After Fajr & Maghrib)',
    tamil: 'நரக நெருப்பிலிருந்து பாதுகாப்பு (ஃபஜ்ர், மஃரிப் பின்)',
    arabic: 'اللَّهُمَّ أَجِرْنِي مِنَ النَّارِ',
    transliteration: "Allahumma ajirni minan-nar",
    meaning_tamil: 'யா அல்லாஹ்! என்னை நரக நெருப்பிலிருந்து பாதுகாப்பாயாக.',
    meaning_english: 'O Allah, protect me from the Fire.',
    reference: 'Sunan Abu Dawud 5079',
    source: 'Abu Dawud',
    grade: 'Hasan',
    count: 7,
  },

  // FOOD
  {
    id: 'food-1',
    category: 'food',
    title: 'Before Eating',
    tamil: 'சாப்பிடுவதற்கு முன் துஆ',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillah',
    meaning_tamil: 'அல்லாஹ்வின் பெயரால்',
    meaning_english: 'In the name of Allah.',
    reference: 'Sahih al-Bukhari 5376',
    source: 'Bukhari',
    grade: 'Sahih',
    count: 1,
    note: 'If you forget to say it at the beginning, say: بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ (Bismillahi awwalahu wa akhirahu)',
  },
  {
    id: 'food-2',
    category: 'food',
    title: 'After Eating',
    tamil: 'சாப்பிட்ட பின் துஆ',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    transliteration: "Al-hamdu lillahi alladhi at'amana wa saqana wa ja'alana Muslimin",
    meaning_tamil: 'எங்களுக்கு சாப்பிட வைத்தவனும் குடிக்க வைத்தவனும் முஸ்லிம்களாக ஆக்கியவனுமான அல்லாஹ்வுக்கே புகழ்.',
    meaning_english: 'All praise is for Allah who fed us, gave us drink, and made us Muslims.',
    reference: 'Sunan Abu Dawud 3850',
    source: 'Abu Dawud',
    grade: 'Sahih',
    count: 1,
  },

  // TRAVEL
  {
    id: 'travel-1',
    category: 'travel',
    title: 'Before Travelling',
    tamil: 'பயணம் மேற்கொள்வதற்கு முன் துஆ',
    arabic: 'اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
    transliteration: "Allahu Akbar, Allahu Akbar, Allahu Akbar. Subhana alladhi sakhkhara lana hadha wa ma kunna lahu muqrinin wa inna ila rabbina la-munqalibun",
    meaning_tamil: 'அல்லாஹு அக்பர் (3 முறை). இதை எங்களுக்கு அடிபணியச் செய்தவன் தூய்மையானவன், இல்லாவிட்டால் இதை நாம் கட்டுப்படுத்திருக்க மாட்டோம். நாம் நிச்சயமாக நம் ரப்பிடம் திரும்புவோம்.',
    meaning_english: 'Allah is the Greatest (x3). How perfect He is, the One Who has placed this (transport) at our service, and we ourselves would not have been capable of that, and to our Lord is our final destiny.',
    reference: 'Sunan Abu Dawud 2602, at-Tirmidhi 3447',
    source: 'Abu Dawud & Tirmidhi',
    grade: 'Sahih',
    count: 1,
  },

  // PARENTS
  {
    id: 'parents-1',
    category: 'parents',
    title: 'Dua for Parents',
    tamil: 'பெற்றோருக்காக துஆ',
    arabic: 'رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    transliteration: "Rabbi irhamhuma kama rabbayani saghiran",
    meaning_tamil: 'என் இறைவனே! என் பெற்றோரை நீ அரவணைப்பாயாக, அவர்கள் என்னை சிறுவயதில் வளர்த்ததைப் போல.',
    meaning_english: 'My Lord, have mercy upon them as they brought me up [when I was] small.',
    reference: 'Quran 17:24',
    source: 'Quran',
    grade: 'Quran',
    count: 1,
  },

  // FORGIVENESS
  {
    id: 'forgiveness-1',
    category: 'forgiveness',
    title: 'Sayyid al-Istighfar — The Best Seeking of Forgiveness',
    tamil: 'சய்யிதுல் இஸ்திஃஃபார் — மன்னிப்பு கோரும் சிறந்த துஆ',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: "Allahumma anta Rabbi la ilaha illa anta, khalaqtani wa ana 'abduka, wa ana 'ala 'ahdika wa wa'dika mastata'tu, a'udhu bika min sharri ma sana'tu, abu'u laka bini'matika 'alayya, wa abu'u laka bidhanbi faghfir li fa innahu la yaghfiru al-dhunuba illa anta",
    meaning_tamil: 'அல்லாஹ்வே! நீ என் இறைவன், உன்னையன்றி வணக்கத்திற்குரியவன் யாருமில்லை. நீ என்னை படைத்தாய், நான் உன் அடியான். என்னால் இயன்ற வரையில் உன் உடன்படிக்கை மீது நிலையாக இருக்கிறேன். நான் செய்தவற்றின் தீமையிலிருந்து உன்னிடம் அடைக்கலம் தேடுகிறேன். உன் அருளை ஏற்றுக்கொள்கிறேன், என் பாவங்களை ஒப்புக்கொள்கிறேன், என்னை மன்னிப்பாயாக, ஏனென்றால் உன்னையன்றி பாவங்களை மன்னிப்பவர் யாருமில்லை.',
    meaning_english: 'O Allah, You are my Lord. There is no god but You. You created me and I am Your slave. I am bound by Your covenant and promise as best as I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for there is none who forgives sins except You.',
    reference: 'Sahih al-Bukhari 6306',
    source: 'Bukhari',
    grade: 'Sahih',
    count: 1,
    note: "The Prophet ﷺ said: 'Whoever says this with conviction in the morning and dies before evening will be among the people of Paradise.'",
  },

  // MASJID
  {
    id: 'masjid-1',
    category: 'masjid',
    title: 'Entering the Masjid',
    tamil: 'மஸ்ஜிதில் நுழையும்போது துஆ',
    arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    transliteration: "Allahumma iftah li abwaba rahmatik",
    meaning_tamil: 'அல்லாஹ்வே! எனக்காக உன் ரஹ்மத்தின் கதவுகளை திறந்தருள்வாயாக.',
    meaning_english: 'O Allah, open for me the gates of Your mercy.',
    reference: 'Sahih Muslim 713',
    source: 'Muslim',
    grade: 'Sahih',
    count: 1,
  },
  {
    id: 'masjid-2',
    category: 'masjid',
    title: 'Leaving the Masjid',
    tamil: 'மஸ்ஜிதிலிருந்து வெளியேறும்போது துஆ',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    transliteration: "Allahumma inni as'aluka min fadlik",
    meaning_tamil: 'அல்லாஹ்வே! உன் அருளைத் தேடுகிறேன்.',
    meaning_english: 'O Allah, I ask You for Your bounty.',
    reference: 'Sahih Muslim 713',
    source: 'Muslim',
    grade: 'Sahih',
    count: 1,
  },

  // ANXIETY
  {
    id: 'anxiety-1',
    category: 'anxiety',
    title: 'Dua for Anxiety and Grief',
    tamil: 'கவலை மற்றும் துயரத்திற்கான துஆ',
    arabic: 'اللَّهُمَّ إِنِّي عَبْدُكَ ابْنُ عَبْدِكَ ابْنُ أَمَتِكَ نَاصِيَتِي بِيَدِكَ مَاضٍ فِيَّ حُكْمُكَ عَدْلٌ فِيَّ قَضَاؤُكَ أَسْأَلُكَ بِكُلِّ اسْمٍ هُوَ لَكَ سَمَّيْتَ بِهِ نَفْسَكَ أَوْ أَنْزَلْتَهُ فِي كِتَابِكَ أَوْ عَلَّمْتَهُ أَحَدًا مِنْ خَلْقِكَ أَوِ اسْتَأْثَرْتَ بِهِ فِي عِلْمِ الْغَيْبِ عِنْدَكَ أَنْ تَجْعَلَ الْقُرْآنَ رَبِيعَ قَلْبِي وَنُورَ صَدْرِي وَجَلَاءَ حُزْنِي وَذَهَابَ هَمِّي',
    transliteration: "Allahumma inni 'abduka ibnu 'abdika ibnu amatika nasiyati bi yadika madin fiyya hukmuka 'adlun fiyya qada'uka as'aluka bikulli ismin huwa laka sammayta bihi nafsaka aw anzaltahu fi kitabika aw 'allamtahu ahadan min khalqika aw ista'tharta bihi fi 'ilm al-ghaybi 'indaka an taj'ala al-Qurana rabi'a qalbi wa nura sadri wa jala'a huzni wa dhahaba hammi",
    meaning_tamil: 'அல்லாஹ்வே! நான் உன் அடியான், உன் ஆண் அடியானின் மகன், உன் பெண் அடியானின் மகன். என் முன்னெற்றி உன் கையில் உள்ளது. உன் தீர்ப்பு என்மீது நடக்கிறது, என்மீதான உன் விதி நீதியானது... குர்ஆனை என் இதயத்தின் இளவேனிலாகவும், நெஞ்சின் ஒளியாகவும், துயரத்தை நீக்குவதாகவும், கவலையை போக்குவதாகவும் ஆக்குவாயாக.',
    meaning_english: "O Allah, I am Your slave, son of Your male slave, son of Your female slave. My forehead is in Your hand. Your judgment upon me is assured, and Your decree concerning me is just... Make the Quran the spring of my heart, the light of my chest, the departure of my sadness and the release of my anxiety.",
    reference: 'Musnad Ahmad 3712',
    source: 'Ahmad',
    grade: 'Sahih',
    count: 1,
  },

  // PROTECTION
  {
    id: 'protection-1',
    category: 'protection',
    title: 'Ayat al-Kursi — The Throne Verse',
    tamil: 'ஆயத்துல் குர்ஸி — அரியாசன வசனம்',
    arabic: 'اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ...',
    transliteration: "Allahu la ilaha illa Huwa al-Hayyu al-Qayyum...",
    meaning_tamil: 'அல்லாஹ் — அவனைத் தவிர வணக்கத்திற்குரியவன் யாரும் இல்லை. அவன் என்றும் உயிருடன் இருப்பவன், அனைத்தையும் நிலைநிறுத்துபவன்... (குர்ஆன் 2:255)',
    meaning_english: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence... (Quran 2:255)',
    reference: 'Quran 2:255 | Sahih al-Bukhari 2311',
    source: 'Quran',
    grade: 'Quran',
    count: 1,
    note: "Whoever recites Ayat al-Kursi after each obligatory prayer, nothing will prevent him from entering Paradise except death. (Sahih - Ibn Hibban 2024)",
  },

  // RIZQ
  {
    id: 'rizq-1',
    category: 'rizq',
    title: 'Dua for Rizq (Provision)',
    tamil: 'ரிஸ்கிற்காக துஆ',
    arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
    transliteration: "Allahumma akfini bihalалika 'an haramika wa aghнini bifadlika 'amman siwak",
    meaning_tamil: 'அல்லாஹ்வே! உன் ஹலாலால் என்னை ஹராமிலிருந்து போதும்படி செய்வாயாக, உன் கருணையால் உன்னையன்றி மற்றவர்களிடம் தேவைப்படாமல் ஆக்குவாயாக.',
    meaning_english: "O Allah, suffice me with what You have allowed instead of what You have forbidden, and make me independent of all others besides You.",
    reference: 'Sunan at-Tirmidhi 3563',
    source: 'Tirmidhi',
    grade: 'Hasan',
    count: 1,
  },

  // RAMADAN
  {
    id: 'ramadan-1',
    category: 'ramadan',
    title: 'Dua for Breaking Fast (Iftar)',
    tamil: 'இஃப்தார் துஆ',
    arabic: 'اللَّهُمَّ لَكَ صُمْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ',
    transliteration: "Allahumma laka sumtu wa 'ala rizqika aftartu",
    meaning_tamil: 'அல்லாஹ்வே! உனக்காக நோன்பு நோற்றேன், உன் ரிஸ்கை கொண்டே நோன்பு விட்டேன்.',
    meaning_english: 'O Allah, for You I have fasted and upon Your provision I have broken my fast.',
    reference: 'Sunan Abu Dawud 2358',
    source: 'Abu Dawud',
    grade: 'Mursal (weak chain, widely practiced)',
    count: 1,
    note: "Note: The chain for this narration is weak (mursal), but it is widely used. Another authentic version: 'Dhahaba al-zama' wa ibtallatil 'urooq wa thabata al-ajr in sha Allah' (Abu Dawud 2357 — Hasan).",
  },

  // ILLNESS
  {
    id: 'illness-1',
    category: 'illness',
    title: 'Dua for the Sick',
    tamil: 'நோயாளிகளுக்காக துஆ',
    arabic: 'اللَّهُمَّ رَبَّ النَّاسِ مُذْهِبَ الْبَاسِ اشْفِ أَنْتَ الشَّافِي لَا شَافِيَ إِلَّا أَنْتَ شِفَاءً لَا يُغَادِرُ سَقَمًا',
    transliteration: "Allahumma rabban-nasi mudhhibal-ba'si, ishfi antash-shafi, la shafiya illa anta, shifa'an la yughadiru saqaman",
    meaning_tamil: 'மனிதர்களின் இறைவனே! துன்பத்தை நீக்குபவனே! குணமளிப்பாயாக, நீயே குணமளிப்பவன். உன்னைத் தவிர வேறு குணமளிப்பவர் இல்லை. நோயின் அறிகுறியே இல்லாதவாறு முழுமையான சுகத்தை வழங்குவாயாக.',
    meaning_english: 'O Allah, Lord of mankind, the One who relieves hardship, grant healing, for You are the Healer. There is no healer but You, a healing that leaves no trace of sickness.',
    reference: 'Sahih al-Bukhari 5743',
    source: 'Bukhari',
    grade: 'Sahih',
    count: 1,
  },

  // MARRIAGE
  {
    id: 'marriage-1',
    category: 'marriage',
    title: 'Congratulating the Newlyweds',
    tamil: 'மணமக்களுக்கு வாழ்த்து துஆ',
    arabic: 'بَارَكَ اللَّهُ لَكَ، وَبَارَكَ عَلَيْكَ، وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ',
    transliteration: "Barakallahu laka, wa baraka 'alayka, wa jama'a baynakuma fi khayr",
    meaning_tamil: 'அல்லாஹ் உங்களுக்கு பரக்கத் செய்வானாக, உங்கள் மீது பரக்கத் பொழிவானாக, உங்கள் இருவரையும் நன்மையில் ஒன்றிணைப்பானாக.',
    meaning_english: 'May Allah bless for you, and may He bless on you, and combine both of you in good.',
    reference: 'Sunan Abu Dawud 2130',
    source: 'Abu Dawud',
    grade: 'Sahih',
    count: 1,
  },

  // NEW BULK ADDITIONS
  {
    id: 'morning-4',
    category: 'morning',
    title: 'Seeking Beneficial Knowledge',
    tamil: 'பயனுள்ள கல்வி கோரும் துஆ',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
    transliteration: "Allahumma inni as'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbalan",
    meaning_tamil: 'யா அல்லாஹ்! நான் உன்னிடம் பயனுள்ள கல்வியையும், தூய்மையான உணவையும் (ரிஸ்க்), ஏற்றுக்கொள்ளப்படும் நற்செயல்களையும் கேட்கிறேன்.',
    meaning_english: 'O Allah, I ask You for beneficial knowledge, goodly provision, and acceptable deeds.',
    reference: 'Sunan Ibn Majah 925',
    source: 'Ibn Majah',
    grade: 'Sahih',
    count: 1,
  },
  {
    id: 'evening-2',
    category: 'evening',
    title: 'Protection from Harm',
    tamil: 'தீங்குகளிலிருந்து பாதுகாப்பு',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: "Bismillahil-ladhi la yadurru ma'as-mihi shai'un fil-ardi wa la fis-sama'i wa huwas-sami'ul-'alim",
    meaning_tamil: 'அல்லாஹ்வின் பெயரால், அவனது பெயருடன் பூமியிலோ வானத்திலோ எந்தப் பொருளும் தீங்கு செய்ய முடியாது. அவன் செவியுறுபவன், நன்கறிபவன்.',
    meaning_english: 'In the name of Allah, with whose name nothing on earth or in the heavens can cause harm, and He is the Hearing, the Knowing.',
    reference: 'Sunan Abu Dawud 5088',
    source: 'Abu Dawud',
    grade: 'Sahih',
    count: 3,
  },
  {
    id: 'sleep-3',
    category: 'sleep',
    title: 'Placing Trust in Allah before Sleep',
    tamil: 'அல்லாஹ்விடம் பொறுப்பை ஒப்படைத்தல்',
    arabic: 'اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ',
    transliteration: "Allahumma aslamtu nafsi ilayk, wa wajjahtu wajhi ilayk, wa fawwadtu amri ilayk",
    meaning_tamil: 'யா அல்லாஹ்! என் உயிரை உன்னிடம் ஒப்படைத்தேன். என் முகத்தை உன்பால் திருப்பினேன். என் காரியங்களை உன்னிடமே விட்டுவிட்டேன்.',
    meaning_english: 'O Allah, I submit my soul to You, I turn my face to You, and I entrust my affairs to You.',
    reference: 'Sahih al-Bukhari 247',
    source: 'Bukhari',
    grade: 'Sahih',
    count: 1,
  },
  {
    id: 'food-3',
    category: 'food',
    title: 'Dua for the Host',
    tamil: 'உணவளித்தவருக்காக துஆ',
    arabic: 'اللَّهُمَّ بَارِكْ لَهُمْ فِيمَا رَزَقْتَهُمْ، وَاغْفِرْ لَهُمْ وَارْحَمْهُمْ',
    transliteration: "Allahumma barik lahum fima razaqtahum, waghfir lahum warhamhum",
    meaning_tamil: 'யா அல்லாஹ்! நீ இவர்களுக்கு வழங்கிய உணவில் பரக்கத் செய்வாயாக, இவர்களை மன்னித்து அருள்புரிவாயாக.',
    meaning_english: 'O Allah, bless them in what You have provided for them, forgive them, and have mercy upon them.',
    reference: 'Sahih Muslim 2042',
    source: 'Muslim',
    grade: 'Sahih',
    count: 1,
  },
  {
    id: 'travel-2',
    category: 'travel',
    title: 'Dua for Returning from Travel',
    tamil: 'பயணத்திலிருந்து திரும்பும்போது துஆ',
    arabic: 'آيِبُونَ، تَائِبُونَ، عَابِدُونَ، لِرَبِّنَا حَامِدُونَ',
    transliteration: "Ayibuna, ta'ibuna, 'abiduna, li-Rabbina hamidun",
    meaning_tamil: 'நாங்கள் (எங்கள் ஊருக்குத்) திரும்புபவர்கள்; பாவமன்னிப்புக் கோருபவர்கள்; எங்கள் இறைவனை வணங்குபவர்கள்; அவனையே புகழ்ந்தவர்கள் ஆவோம்.',
    meaning_english: 'We are returning, repenting, worshipping, and praising our Lord.',
    reference: 'Sahih Muslim 1342',
    source: 'Muslim',
    grade: 'Sahih',
    count: 1,
  },
  {
    id: 'anxiety-2',
    category: 'anxiety',
    title: 'Dua for Distress (Dua of Yunus AS)',
    tamil: 'துன்பத்தின் போது ஓதும் துஆ (யூனுஸ் அலை)',
    arabic: 'لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ',
    transliteration: "La ilaha illa anta, subhanaka inni kuntu minadh-dhalimin",
    meaning_tamil: 'உன்னையன்றி வணக்கத்திற்குரியவன் வேறு யாருமில்லை. நீ தூய்மையானவன். நிச்சயமாக நான் அநீதியிழைத்தவர்களில் ஒருவனாகிவிட்டேன்.',
    meaning_english: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
    reference: 'Sunan at-Tirmidhi 3505',
    source: 'Tirmidhi',
    grade: 'Sahih',
    count: 1,
    note: 'No Muslim supplicates with this for anything except that Allah answers him.',
  },
  {
    id: 'protection-2',
    category: 'protection',
    title: 'Seeking Refuge from Evil',
    tamil: 'அனைத்து தீமைகளிலிருந்தும் பாதுகாப்பு',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    meaning_tamil: 'அல்லாஹ் படைத்தவற்றின் தீங்கிலிருந்து அவனது முழுமையான வார்த்தைகளைக்கொண்டு நான் பாதுகாப்புத் தேடுகிறேன்.',
    meaning_english: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
    reference: 'Sahih Muslim 2708',
    source: 'Muslim',
    grade: 'Sahih',
    count: 3,
  },
  {
    id: 'rizq-2',
    category: 'rizq',
    title: 'Dua for Paying off Debts',
    tamil: 'கடன்களை அடைக்க துஆ',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ، وَغَلَبَةِ الرِّجَالِ',
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan, wal-'ajzi wal-kasal, wal-bukhli wal-jubn, wa dala'id-dayni wa ghalabatir-rijal",
    meaning_tamil: 'யா அல்லாஹ்! கவலை, துக்கம், இயலாமை, சோம்பேறித்தனம், கஞ்சத்தனம், கோழைத்தனம், கடனின் சுமை மற்றும் மனிதர்களின் அடக்குமுறை ஆகியவற்றிலிருந்து உன்னிடம் பாதுகாப்புத் தேடுகிறேன்.',
    meaning_english: 'O Allah, I seek refuge in You from anxiety and sorrow, weakness and laziness, miserliness and cowardice, the burden of debts and from being overpowered by men.',
    reference: 'Sahih al-Bukhari 2893',
    source: 'Bukhari',
    grade: 'Sahih',
    count: 1,
  },
  {
    id: 'forgiveness-2',
    category: 'forgiveness',
    title: 'Dua for Sincere Repentance',
    tamil: 'உண்மையான தவ்பா',
    arabic: 'رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ، إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ',
    transliteration: "Rabbighfir li wa tub 'alayya, innaka antat-Tawwabur-Rahim",
    meaning_tamil: 'என் இறைவா! என்னை மன்னிப்பாயாக! என் தவ்பாவை ஏற்றுக்கொள்வாயாக. நிச்சயமாக நீயே தவ்பாவை ஏற்றுக்கொள்பவனும், அளவற்ற அருளாளனுமாவாய்.',
    meaning_english: 'My Lord, forgive me and accept my repentance, You are the Ever-Relenting, the Most Merciful.',
    reference: 'Sunan Abu Dawud 1516',
    source: 'Abu Dawud',
    grade: 'Sahih',
    count: 100,
  }
];

export function getDuasByCategory(categoryId) {
  return DUAS.filter(d => d.category === categoryId);
}

export function getDua(id) {
  return DUAS.find(d => d.id === id) || null;
}

export function searchDuas(query) {
  const q = query.toLowerCase();
  return DUAS.filter(d =>
    d.title.toLowerCase().includes(q) ||
    d.tamil.toLowerCase().includes(q) ||
    d.meaning_tamil.toLowerCase().includes(q) ||
    d.meaning_english.toLowerCase().includes(q)
  );
}
