const names = [
  ['الرَّحْمَنُ', 'Ar-Rahman', 'The Most Compassionate'],
  ['الرَّحِيمُ', 'Ar-Raheem', 'The Most Merciful'],
  ['الْمَلِكُ', 'Al-Malik', 'The King'],
  ['الْقُدُّوسُ', 'Al-Quddus', 'The Most Holy'],
  ['السَّلاَمُ', 'As-Salam', 'The Source of Peace'],
  ['الْمُؤْمِنُ', 'Al-Mu’min', 'The Giver of Faith and Security'],
  ['الْمُهَيْمِنُ', 'Al-Muhaymin', 'The Guardian'],
  ['الْعَزِيزُ', 'Al-Aziz', 'The Almighty'],
  ['الْجَبَّارُ', 'Al-Jabbar', 'The Compeller'],
  ['الْمُتَكَبِّرُ', 'Al-Mutakabbir', 'The Supremely Great'],
  ['الْخَالِقُ', 'Al-Khaliq', 'The Creator'],
  ['الْبَارِئُ', 'Al-Bari', 'The Originator'],
  ['الْمُصَوِّرُ', 'Al-Musawwir', 'The Fashioner'],
  ['الْغَفَّارُ', 'Al-Ghaffar', 'The Repeated Forgiver'],
  ['الْقَهَّارُ', 'Al-Qahhar', 'The Subduer'],
  ['الْوَهَّابُ', 'Al-Wahhab', 'The Bestower'],
  ['الرَّزَّاقُ', 'Ar-Razzaq', 'The Provider'],
  ['الْفَتَّاحُ', 'Al-Fattah', 'The Opener'],
  ['اَلْعَلِيمُ', 'Al-Alim', 'The All-Knowing'],
  ['الْقَابِضُ', 'Al-Qabid', 'The Withholder'],
  ['الْبَاسِطُ', 'Al-Basit', 'The Extender'],
  ['الْخَافِضُ', 'Al-Khafid', 'The Abaser'],
  ['الرَّافِعُ', 'Ar-Rafi', 'The Exalter'],
  ['الْمُعِزُّ', 'Al-Muizz', 'The Bestower of Honor'],
  ['المُذِلُّ', 'Al-Mudhill', 'The One Who Humbles'],
  ['السَّمِيعُ', 'As-Sami', 'The All-Hearing'],
  ['الْبَصِيرُ', 'Al-Basir', 'The All-Seeing'],
  ['الْحَكَمُ', 'Al-Hakam', 'The Judge'],
  ['الْعَدْلُ', 'Al-Adl', 'The Utterly Just'],
  ['اللَّطِيفُ', 'Al-Latif', 'The Most Gentle'],
  ['الْخَبِيرُ', 'Al-Khabir', 'The All-Aware'],
  ['الْحَلِيمُ', 'Al-Halim', 'The Forbearing'],
  ['الْعَظِيمُ', 'Al-Azim', 'The Magnificent'],
  ['الْغَفُورُ', 'Al-Ghafur', 'The All-Forgiving'],
  ['الشَّكُورُ', 'Ash-Shakur', 'The Most Appreciative'],
  ['الْعَلِيُّ', 'Al-Aliyy', 'The Most High'],
  ['الْكَبِيرُ', 'Al-Kabir', 'The Most Great'],
  ['الْحَفِيظُ', 'Al-Hafiz', 'The Preserver'],
  ['المُقيِت', 'Al-Muqit', 'The Sustainer'],
  ['الْحسِيبُ', 'Al-Hasib', 'The Reckoner'],
  ['الْجَلِيلُ', 'Al-Jalil', 'The Majestic'],
  ['الْكَرِيمُ', 'Al-Karim', 'The Most Generous'],
  ['الرَّقِيبُ', 'Ar-Raqib', 'The Watchful'],
  ['الْمُجِيبُ', 'Al-Mujib', 'The Responsive'],
  ['الْوَاسِعُ', 'Al-Wasi', 'The All-Encompassing'],
  ['الْحَكِيمُ', 'Al-Hakim', 'The All-Wise'],
  ['الْوَدُودُ', 'Al-Wadud', 'The Most Loving'],
  ['الْمَجِيدُ', 'Al-Majid', 'The Most Glorious'],
  ['الْبَاعِثُ', 'Al-Baith', 'The Resurrector'],
  ['الشَّهِيدُ', 'Ash-Shahid', 'The Witness'],
  ['الْحَقُّ', 'Al-Haqq', 'The Truth'],
  ['الْوَكِيلُ', 'Al-Wakil', 'The Trustee'],
  ['الْقَوِيُّ', 'Al-Qawiyy', 'The All-Strong'],
  ['الْمَتِينُ', 'Al-Matin', 'The Firm'],
  ['الْوَلِيُّ', 'Al-Waliyy', 'The Protecting Friend'],
  ['الْحَمِيدُ', 'Al-Hamid', 'The Praiseworthy'],
  ['الْمُحْصِي', 'Al-Muhsi', 'The One Who Counts All'],
  ['الْمُبْدِئُ', 'Al-Mubdi', 'The Originator'],
  ['الْمُعِيدُ', 'Al-Muid', 'The Restorer'],
  ['الْمُحْيِي', 'Al-Muhyi', 'The Giver of Life'],
  ['اَلْمُمِيتُ', 'Al-Mumit', 'The Creator of Death'],
  ['الْحَيُّ', 'Al-Hayy', 'The Ever-Living'],
  ['الْقَيُّومُ', 'Al-Qayyum', 'The Self-Subsisting Sustainer'],
  ['الْوَاجِدُ', 'Al-Wajid', 'The Finder'],
  ['الْمَاجِدُ', 'Al-Majid', 'The Noble'],
  ['الْواحِدُ', 'Al-Wahid', 'The One'],
  ['اَلاَحَدُ', 'Al-Ahad', 'The Unique'],
  ['الصَّمَدُ', 'As-Samad', 'The Eternal Refuge'],
  ['الْقَادِرُ', 'Al-Qadir', 'The All-Powerful'],
  ['الْمُقْتَدِرُ', 'Al-Muqtadir', 'The Omnipotent'],
  ['الْمُقَدِّمُ', 'Al-Muqaddim', 'The One Who Advances'],
  ['الْمُؤَخِّرُ', 'Al-Mu’akhkhir', 'The One Who Delays'],
  ['الأوَّلُ', 'Al-Awwal', 'The First'],
  ['الآخِرُ', 'Al-Akhir', 'The Last'],
  ['الظَّاهِرُ', 'Az-Zahir', 'The Manifest'],
  ['الْبَاطِنُ', 'Al-Batin', 'The Most Near and Hidden'],
  ['الْوَالِي', 'Al-Wali', 'The Governor'],
  ['الْمُتَعَالِي', 'Al-Mutaali', 'The Most Exalted'],
  ['الْبَرُّ', 'Al-Barr', 'The Source of Goodness'],
  ['التَّوَابُ', 'At-Tawwab', 'The Accepter of Repentance'],
  ['الْمُنْتَقِمُ', 'Al-Muntaqim', 'The Just Retributor'],
  ['العَفُوُّ', 'Al-Afuww', 'The Pardoner'],
  ['الرَّؤُوفُ', 'Ar-Rauf', 'The Most Kind'],
  ['مَالِكُ الْمُلْكِ', 'Malik-ul-Mulk', 'Owner of All Sovereignty'],
  ['ذُو الْجَلَالِ وَالْإِكْرَامِ', 'Dhul-Jalali wal-Ikram', 'Lord of Majesty and Honor'],
  ['الْمُقْسِطُ', 'Al-Muqsit', 'The Equitable'],
  ['الْجَامِعُ', 'Al-Jami', 'The Gatherer'],
  ['الْغَنِيُّ', 'Al-Ghaniyy', 'The Self-Sufficient'],
  ['الْمُغْنِي', 'Al-Mughni', 'The Enricher'],
  ['اَلْمَانِعُ', 'Al-Mani', 'The Preventer'],
  ['الضَّارَّ', 'Ad-Darr', 'The One Who Allows Adversity'],
  ['النَّافِعُ', 'An-Nafi', 'The Bestower of Benefit'],
  ['النُّورُ', 'An-Nur', 'The Light'],
  ['الْهَادِي', 'Al-Hadi', 'The Guide'],
  ['الْبَدِيعُ', 'Al-Badi', 'The Incomparable Originator'],
  ['اَلْبَاقِي', 'Al-Baqi', 'The Everlasting'],
  ['الْوَارِثُ', 'Al-Warith', 'The Inheritor'],
  ['الرَّشِيدُ', 'Ar-Rashid', 'The Guide to the Right Way'],
  ['الصَّبُورُ', 'As-Sabur', 'The Most Patient'],
];

export const NAMES_OF_ALLAH = names.map(([arabic, transliteration, meaning], index) => ({
  number: index + 1,
  arabic,
  transliteration,
  meaning,
  meaningTamil: [
    'அளவற்ற அருளாளன்',
    'நிகரற்ற அன்புடையோன்',
    'அரசன்',
    'மிகத் தூயவன்',
    'சாந்தி அளிப்பவன்',
    'பாதுகாப்பும் நம்பிக்கையும் அளிப்பவன்',
    'கண்காணிப்பவன்',
    'மிகைத்தவன்',
    'யாவற்றையும் அடக்கி ஆள்பவன்',
    'மகத்துவமிக்கவன்',
    'படைப்பவன்',
    'உருவாக்குபவன்',
    'வடிவமைப்பவன்',
    'மீண்டும் மீண்டும் மன்னிப்பவன்',
    'அனைத்தையும் அடக்கி ஆள்பவன்',
    'மகத்தான கொடையாளன்',
    'வாழ்வாதாரம் வழங்குபவன்',
    'திறப்பவன்',
    'அனைத்தையும் அறிந்தவன்',
    'குறுக்குபவன்',
    'விரிவாக்குபவன்',
    'தாழ்த்துபவன்',
    'உயர்த்துபவன்',
    'கண்ணியமளிப்பவன்',
    'தாழ்வை ஏற்படுத்துபவன்',
    'அனைத்தையும் செவியுறுபவன்',
    'அனைத்தையும் பார்ப்பவன்',
    'தீர்ப்பளிப்பவன்',
    'முற்றிலும் நீதியானவன்',
    'நுட்பமாக அறிபவன்',
    'அனைத்தையும் நன்கறிந்தவன்',
    'சகிப்புத்தன்மையுடையவன்',
    'மகத்தானவன்',
    'மிகவும் மன்னிப்பவன்',
    'நன்றியை ஏற்றுக் கொள்பவன்',
    'மிக உயர்ந்தவன்',
    'மகா பெரியவன்',
    'பாதுகாப்பவன்',
    'உணவளிப்பவன்',
    'கணக்கிடுபவன்',
    'மகிமைமிக்கவன்',
    'மிகவும் கண்ணியமானவன்',
    'கண்காணிப்பவன்',
    'பிரார்த்தனைக்குப் பதிலளிப்பவன்',
    'விசாலமானவன்',
    'ஞானமிக்கவன்',
    'அன்புடையவன்',
    'புகழும் மகிமையும் உடையவன்',
    'மீண்டும் எழுப்புபவன்',
    'சாட்சியாக இருப்பவன்',
    'முற்றிலும் உண்மையானவன்',
    'பொறுப்பேற்பவன்',
    'மிகுந்த வலிமையுடையவன்',
    'உறுதியான வலிமையுடையவன்',
    'பாதுகாவலன்',
    'புகழுக்குரியவன்',
    'அனைத்தையும் கணக்கிடுபவன்',
    'முதன்முதலில் படைப்பவன்',
    'மீண்டும் கொண்டுவருபவன்',
    'உயிரளிப்பவன்',
    'மரணத்தை ஏற்படுத்துபவன்',
    'என்றும் உயிருள்ளவன்',
    'என்றும் நிலைத்திருந்து அனைத்தையும் நிர்வகிப்பவன்',
    'தேவையான அனைத்தையும் பெற்றவன்',
    'மகிமையும் கண்ணியமும் உடையவன்',
    'ஒருவனானவன்',
    'தனித்துவமான ஒருவன்',
    'அனைவரும் சார்ந்திருக்கும் நிரந்தரமானவன்',
    'அனைத்திற்கும் ஆற்றலுடையவன்',
    'முழு ஆற்றலுடையவன்',
    'முன்னிறுத்துபவன்',
    'பின்னிறுத்துபவன்',
    'முதலானவன்',
    'இறுதியானவன்',
    'வெளிப்படையானவன்',
    'மறைவானவன்',
    'ஆள்பவன்',
    'மிக உயர்ந்தவன்',
    'நன்மையின் ஊற்றானவன்',
    'பாவமன்னிப்பை ஏற்றுக்கொள்பவன்',
    'நீதியான முறையில் தண்டிப்பவன்',
    'பாவங்களை அழித்து மன்னிப்பவன்',
    'மிகுந்த இரக்கமுடையவன்',
    'அனைத்து ஆட்சிக்கும் உரிமையாளன்',
    'மகத்துவமும் கண்ணியமும் உடையவன்',
    'நீதியுடன் நடப்பவன்',
    'ஒன்றுசேர்ப்பவன்',
    'எவரிடமும் தேவையற்றவன்',
    'செல்வம் அளிப்பவன்',
    'தடுப்பவன்',
    'துன்பத்தை ஏற்படுத்த அனுமதிப்பவன்',
    'நன்மை அளிப்பவன்',
    'ஒளியானவன்',
    'நேர்வழி காட்டுபவன்',
    'முன்மாதிரியின்றிப் படைப்பவன்',
    'என்றும் நிலைத்திருப்பவன்',
    'அனைத்திற்கும் இறுதி உரிமையாளன்',
    'நேர்வழி காட்டுபவன்',
    'மிகுந்த பொறுமையுடையவன்',
  ][index],
}));
